// src/examples/aspect-ratio/aspect-ratio-ratios.tsx
import { AspectRatio } from "@/components/figma/AspectRatio";

const RATIOS = [
  { label: "1 / 1", value: 1 },
  { label: "4 / 3", value: 4 / 3 },
  { label: "16 / 9", value: 16 / 9 },
  { label: "21 / 9", value: 21 / 9 },
];

export const AspectRatioRatios = () => {
  return (
    <div className="flex w-full flex-col gap-4">
      {RATIOS.map((r) => (
        <div key={r.label}>
          <p className="mb-1 text-xs text-muted-foreground">{r.label}</p>
          <AspectRatio ratio={r.value} className="rounded-medium bg-muted">
            <div className="flex h-full items-center justify-center text-sm text-muted-foreground">
              {r.label}
            </div>
          </AspectRatio>
        </div>
      ))}
    </div>
  );
};

// src/examples/aspect-ratio/aspect-ratio-ratios.vue
<script setup lang="ts">
const ratios = [
  { label: '1 / 1', value: '1 / 1' },
  { label: '4 / 3', value: '4 / 3' },
  { label: '16 / 9', value: '16 / 9' },
  { label: '21 / 9', value: '21 / 9' },
]
</script>

<template>
  <div :style="{ display: 'flex', flexDirection: 'column', gap: '16px', width: '100%' }">
    <div v-for="r in ratios" :key="r.label">
      <p :style="{ margin: '0 0 4px', fontFamily: 'var(--font-lexend), sans-serif', fontSize: '12px', color: 'var(--muted-foreground)' }">
        {{ r.label }}
      </p>
      <div
        :style="{
          aspectRatio: r.value,
          width: '100%',
          borderRadius: 'var(--radius-medium)',
          background: 'var(--muted)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          fontFamily: 'var(--font-lexend), sans-serif',
          fontSize: '14px',
          color: 'var(--muted-foreground)',
        }"
      >
        {{ r.label }}
      </div>
    </div>
  </div>
</template>
