// src/examples/label/label-default.tsx
import { Label } from "@/components/figma/Label";

export const LabelDefault = () => {
  return (
    <div className="flex flex-col gap-2">
      <Label htmlFor="email">Email address</Label>
      <input
        id="email"
        type="email"
        placeholder="you@example.com"
        className="h-9 rounded-medium border border-border-input bg-background px-200 text-sm text-foreground placeholder:text-placeholder outline-none focus:ring-2 focus:ring-ring"
      />
    </div>
  );
};

// src/examples/label/label-default.vue
<template>
  <div :style="{ display: 'flex', flexDirection: 'column', gap: '8px' }">
    <label for="email" :style="{
      display: 'inline-flex',
      alignItems: 'center',
      gap: 'var(--space-050)',
      fontSize: '14px',
      fontWeight: 500,
      lineHeight: 1,
      color: 'var(--foreground)',
      userSelect: 'none',
    }">Email address</label>
    <input
      id="email"
      type="email"
      placeholder="you@example.com"
      :style="{
        height: '36px',
        borderRadius: 'var(--radius-medium)',
        border: '1px solid var(--border-input)',
        background: 'var(--background)',
        padding: '0 var(--space-200)',
        fontSize: '14px',
        color: 'var(--foreground)',
        outline: 'none',
      }"
    />
  </div>
</template>
