// src/examples/key-pair-value/key-pair-value-vertical.tsx
import { KeyPairValue } from "@/components/figma/KeyPairValue";

export const KeyPairValueVertical = () => (
  <div className="grid grid-cols-2 sm:grid-cols-3 gap-x-8 gap-y-2 p-6 w-full min-w-80 max-w-xl">
    <KeyPairValue label="Full Name" orientation="vertical">
      <span>Alice Johnson</span>
    </KeyPairValue>
    <KeyPairValue label="Email" orientation="vertical">
      <span>alice@example.com</span>
    </KeyPairValue>
    <KeyPairValue label="Role" orientation="vertical">
      <span>Product Designer</span>
    </KeyPairValue>
    <KeyPairValue label="Department" orientation="vertical">
      <span>Design</span>
    </KeyPairValue>
    <KeyPairValue label="Location" orientation="vertical">
      <span>San Francisco, CA</span>
    </KeyPairValue>
    <KeyPairValue label="Joined" orientation="vertical">
      <span>Jan 2024</span>
    </KeyPairValue>
  </div>
);

// src/examples/key-pair-value/key-pair-value-vertical.vue
<script setup lang="ts">
const items = [
  { label: 'Full Name', value: 'Alice Johnson' },
  { label: 'Email', value: 'alice@example.com' },
  { label: 'Role', value: 'Product Designer' },
  { label: 'Department', value: 'Design' },
  { label: 'Location', value: 'San Francisco, CA' },
  { label: 'Joined', value: 'Jan 2024' },
]

const keyStyle = {
  fontFamily: '\'Lexend\', sans-serif',
  fontWeight: 400,
  fontSize: '14px',
  lineHeight: '20px',
  color: 'var(--subtlest, #ada5a5)',
}

const valueStyle = {
  fontFamily: '\'Lexend\', sans-serif',
  fontWeight: 500,
  fontSize: '14px',
  lineHeight: '20px',
  color: 'var(--foreground, #2e2b2b)',
}
</script>

<template>
  <div :style="{ padding: '24px', width: '100%', maxWidth: '576px' }">
    <div :style="{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '0 32px' }">
      <div
        v-for="(item, i) in items"
        :key="i"
        :style="{ display: 'flex', flexDirection: 'column', gap: '4px', padding: '8px 0' }"
      >
        <span :style="keyStyle">{{ item.label }}</span>
        <span :style="valueStyle">{{ item.value }}</span>
      </div>
    </div>
  </div>
</template>
