// src/examples/field/field-default.tsx
import { Field, FieldDescription, FieldLabel } from "@/components/figma/Field";

export const FieldDefault = () => {
  return (
    <Field className="w-64">
      <FieldLabel htmlFor="field-email">Email</FieldLabel>
      <input
        id="field-email"
        type="email"
        placeholder="you@example.com"
        className="h-9 w-full rounded-medium border border-border-input bg-background px-200 text-sm font-lexend text-foreground placeholder:text-placeholder focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-1"
      />
      <FieldDescription>We&apos;ll never share your email.</FieldDescription>
    </Field>
  );
};

// src/examples/field/field-default.vue
<script setup lang="ts">
// Static component — no reactive state needed
</script>

<template>
  <div :style="{ display: 'flex', flexDirection: 'column', gap: 'var(--space-075)', width: '256px' }">
    <label
      for="field-email"
      :style="{
        display: 'inline-flex', alignItems: 'center', gap: '4px',
        fontSize: '0.875rem', fontWeight: 500, lineHeight: 1,
        color: 'var(--foreground)', userSelect: 'none',
      }"
    >Email</label>
    <input
      id="field-email"
      type="email"
      placeholder="you@example.com"
      :style="{
        height: '36px', width: '100%', borderRadius: 'var(--radius-medium)',
        border: '1px solid var(--border-input)', background: 'var(--background)',
        padding: '0 var(--space-200)', fontSize: '0.875rem', color: 'var(--foreground)',
        outline: 'none', boxSizing: 'border-box',
      }"
    />
    <p :style="{ fontSize: '0.75rem', lineHeight: '1.625', color: 'var(--muted-foreground)', margin: 0 }">
      We'll never share your email.
    </p>
  </div>
</template>
