// src/examples/sheet/sheet-default.vue
<script setup lang="ts">
import { ref } from 'vue'

const open = ref(false)
</script>

<template>
  <!-- Trigger -->
  <button
    type="button"
    @click="open = true"
    :style="{
      display: 'inline-flex',
      height: '36px',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 'var(--radius-medium)',
      border: '1px solid var(--border)',
      background: 'var(--background)',
      padding: '0 var(--space-200)',
      fontSize: '14px',
      fontWeight: 500,
      color: 'var(--foreground)',
      cursor: 'pointer',
      fontFamily: 'var(--font-lexend, sans-serif)',
    }"
  >Open Sheet</button>

  <!-- Overlay -->
  <Teleport to="body">
    <div v-if="open">
      <div
        @click="open = false"
        :style="{
          position: 'fixed',
          inset: 0,
          zIndex: 50,
          background: 'rgba(46,43,43,0.4)',
          backdropFilter: 'blur(2px)',
        }"
      />

      <!-- Panel -->
      <div
        :style="{
          position: 'fixed',
          top: 0,
          right: 0,
          bottom: 0,
          zIndex: 50,
          height: '100%',
          width: '75%',
          maxWidth: '384px',
          borderLeft: '1px solid var(--border)',
          background: 'var(--background)',
          padding: 'var(--space-300)',
          display: 'flex',
          flexDirection: 'column',
          fontFamily: 'var(--font-lexend, sans-serif)',
        }"
      >
        <h2 :style="{ fontSize: '18px', fontWeight: 600, color: 'var(--foreground)', marginBottom: '4px' }">
          Edit Profile
        </h2>
        <p :style="{ fontSize: '14px', color: 'var(--muted-foreground)', marginBottom: 'var(--space-200)' }">
          Make changes to your profile here.
        </p>

        <label :style="{ fontSize: '14px', fontWeight: 500, color: 'var(--foreground)', marginBottom: '6px' }">Name</label>
        <input
          type="text"
          value="Muhammad Hasan"
          :style="{
            height: '36px',
            borderRadius: 'var(--radius-medium)',
            border: '1px solid var(--border-input)',
            background: 'var(--background)',
            padding: '0 var(--space-150)',
            fontSize: '14px',
            color: 'var(--foreground)',
            marginBottom: 'var(--space-150)',
            width: '100%',
            fontFamily: 'var(--font-lexend, sans-serif)',
          }"
        />

        <label :style="{ fontSize: '14px', fontWeight: 500, color: 'var(--foreground)', marginBottom: '6px' }">Username</label>
        <input
          type="text"
          value="@mhasan"
          :style="{
            height: '36px',
            borderRadius: 'var(--radius-medium)',
            border: '1px solid var(--border-input)',
            background: 'var(--background)',
            padding: '0 var(--space-150)',
            fontSize: '14px',
            color: 'var(--foreground)',
            marginBottom: 'var(--space-150)',
            width: '100%',
            fontFamily: 'var(--font-lexend, sans-serif)',
          }"
        />

        <div :style="{ marginTop: 'auto', display: 'flex', justifyContent: 'flex-end', gap: 'var(--space-150)' }">
          <button
            type="button"
            @click="open = false"
            :style="{
              display: 'inline-flex', height: '36px', alignItems: 'center', justifyContent: 'center',
              borderRadius: 'var(--radius-medium)', border: '1px solid var(--border)',
              background: 'var(--background)', padding: '0 var(--space-200)',
              fontSize: '14px', fontWeight: 500, color: 'var(--foreground)', cursor: 'pointer',
            }"
          >Cancel</button>
          <button
            type="button"
            @click="open = false"
            :style="{
              display: 'inline-flex', height: '36px', alignItems: 'center', justifyContent: 'center',
              borderRadius: 'var(--radius-medium)', border: '1px solid transparent',
              background: 'var(--primary)', padding: '0 var(--space-200)',
              fontSize: '14px', fontWeight: 500, color: 'var(--primary-foreground)', cursor: 'pointer',
            }"
          >Save Changes</button>
        </div>
      </div>
    </div>
  </Teleport>
</template>

// src/examples/sheet/sheet-default.tsx
"use client";

import {
  Sheet,
  SheetClose,
  SheetContent,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/figma/Sheet";

export const SheetDefault = () => {
  return (
    <Sheet>
      <SheetTrigger className="inline-flex h-9 items-center justify-center rounded-medium border border-border bg-background px-200 text-sm font-medium text-foreground transition-colors hover:bg-muted-hover">
        Open Sheet
      </SheetTrigger>
      <SheetContent side="right">
        <SheetHeader>
          <SheetTitle>Edit Profile</SheetTitle>
          <SheetDescription>Make changes to your profile here.</SheetDescription>
        </SheetHeader>
        <div className="py-200 space-y-150">
          <div className="flex flex-col gap-075">
            <label className="text-sm font-medium text-foreground">Name</label>
            <input
              className="h-9 rounded-medium border border-border-input bg-background px-150 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
              defaultValue="Muhammad Hasan"
            />
          </div>
          <div className="flex flex-col gap-075">
            <label className="text-sm font-medium text-foreground">Username</label>
            <input
              className="h-9 rounded-medium border border-border-input bg-background px-150 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
              defaultValue="@mhasan"
            />
          </div>
        </div>
        <SheetFooter>
          <SheetClose className="inline-flex h-9 items-center justify-center rounded-medium border border-border bg-background px-200 text-sm font-medium text-foreground transition-colors hover:bg-muted-hover">
            Cancel
          </SheetClose>
          <SheetClose className="inline-flex h-9 items-center justify-center rounded-medium bg-primary px-200 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary-hover">
            Save Changes
          </SheetClose>
        </SheetFooter>
      </SheetContent>
    </Sheet>
  );
};
